
[APP]
ENVIRONMENT = "test"
DEBUG = true
# Only accept True or False

[BIGQUERY]
KEY = ""

[SHOPIFY]
SHOP_NAME = ""
SHOP_API_VERSION = ""
ACCESS_TOKEN = ""

[[SHOPIFY.TABLES]]
name = "shopify_orders"
schema = "schema/order.json"

[[SHOPIFY.TABLES]]
name = "shopify_product_variants"
schema = "schema/product_variant.json"

[[SHOPIFY.TABLES]]
name = "shopfy_customer_visits"
schema = "schema/order.json"

[[SHOPIFY.TABLES]]
name = "shopify_orders"
schema = "schema/order.json"

[[SHOPIFY.TABLES]]
name = "shopify_orders"
schema = "schema/order.json"

[[SHOPIFY.TABLES]]
name = "shopify_orders"
schema = "schema/order.json"
