APP:
  ENVIRONMENT: "test"
  DEBUG: True

BIGQUERY:
  # Used to authenticate requests to BQ
  KEY: ""
  # Optional; The dataset name in BQ; Uses SHOPIFY.SHOP_NAME (converted to snake_case) if no option is provided.
  TENANT_NAME: ""
  # Location, or region for the GCP Dataset
  LOCATION: "northamerica-northeast2"
  # Table name and path to schema
  TABLES:
    ORDERS:
      NAME: "shopify_orders"
      SCHEMA: "schema/orders.json"
    CUSTOMER_VISIT:
      NAME: "shopify_customer_visits"
      SCHEMA: "schema/customer_visits.json"
    DISCOUNT_APPLICATION:
      NAME: "shopify_discount_application"
      SCHEMA: "schema/discount_application"
    PRODUCTS:
      NAME: "shopify_products"
      SCHEMA: "schema/shopify_products"
    PRODUCT_VARIANT:
      NAME: "shopify_product_variants"
      SCHEMA: "schema/shopify_products"
    CUSTOMERS:
      NAME: "shopify_customers"
      SCHEMA: "schema/shopify_customers"


SHOPIFY:
  SHOP_NAME: ""
  SHOP_API_VERSION: "2023-07"
   # Authenticates Shopify GraphQL Requests
  ACCESS_TOKEN: ""
  # Specify which channels should be included in the data ingestion
  CHANNELS:
    ORDERS: True
    CUSTOMERS: True
    PRODUCTS: True


