APP:
  ENVIRONMENT: "test"
  DEBUG: True

BIGQUERY:
  # Used to authenticate requests to BQ
  KEY: ""
  PROJECT_NAME: ""
  # Optional; snake_case; The dataset name in BQ; Uses SHOPIFY.SHOP_NAME (converted to snake_case) if no option is provided.
  TENANT_NAME: ""
  # Location, or region for the GCP Dataset
  LOCATION: ""
  # Table name and path to schema
  TABLES:



SHOPIFY:
  SHOP_NAME: ""
  API_VERSION: "2023-07"
   # Authenticates Shopify GraphQL Requests
  ACCESS_TOKEN: ""
  # Specify which channels should be included in the data ingestion
  ENDPOINTS:
    ORDERS:
      ENABLED: True
      TABLES:
        ORDERS:
          TYPENAME: "Order"
          NAME: "shopify_orders"
          SCHEMA: "schema/shopify_order.json"
        CUSTOMER_VISITS:
          TYPENAME: "CustomerVisit"
          NAME: "shopify_customer_visits"
          SCHEMA: "schema/shopify_customer_visit.json"
        DISCOUNT_APPLICATIONS:
          TYPENAME: [ "DiscountCodeApplication", "ManualDiscountApplication", "AutomaticDiscountApplication" ]
          NAME: "shopify_discount_application"
          SCHEMA: "schema/shopify_discount_application.json"
    CUSTOMERS:
      ENABLED: True
      TABLES:
        CUSTOMERS:
          TYPENAME: "Customer"
          NAME: "shopify_customers"
          SCHEMA: "schema/shopify_customer.json"
    PRODUCTS:
      ENABLED: True
      TABLES:
        PRODUCTS:
          TYPENAME: "Product"
          NAME: "shopify_products"
          SCHEMA: "schema/shopify_product.json"
        PRODUCT_VARIANTS:
          TYPENAME: "ProductVariant"
          NAME: "shopify_product_variants"
          SCHEMA: "schema/shopify_product_variant.json"


